In [122]:
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
from sklearn import linear_model

In [123]:
# MULTIVAIRATE REGRESSION
%matplotlib inline

In [124]:
# Equation of Linear Regression with n number of variables
# y = m*x1 + m*x2 + m*x3 ..... m*xn +b

In [125]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [126]:
import math

median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [127]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [128]:
# DATA PREPROCESSING DONE

In [129]:
reg = linear_model.LinearRegression()

# independent variables = 'area','bedrooms','age'
# target variable = 'price'
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [130]:
# List/Array of coeffiecients m1,m2,m3
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [131]:
# value of b
reg.intercept_

383724.99999999994

In [132]:
# trial run 
# price lesser than home with age 15 = 565000
reg.predict([[3000,3,40]])

array([444400.])

In [133]:
# y = m*x1 + m*x2 + m*x3 + b
137.25*3000+-26025*3+-6825*40+383724.99999999994

444399.99999999994

In [134]:
reg.predict([[2500,10,5]])

array([432475.])

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

<h3>Answers:</h3>

53713.86 and 93747.79

In [135]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

<h4>Word to Number</h4>

This is a Python module to convert number words (eg. twenty one) to numeric digits (21). It works for positive numbers upto the range of 999,999,999,999 (i.e. billions).


`pip install word2number`

In [136]:
from word2number import w2n
print('eleven',w2n.word_to_num('eleven'))
print('twenty one: ',w2n.word_to_num('twenty one'))

eleven 11
twenty one:  21


In [137]:
# DO DATA PREPROCESSING

In [138]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [139]:
# map unique numbers used in DataFrame to integers
exp_num = set(df.experience)

def convert_to_num(word):
    return w2n.word_to_num(word)

def map_words_to_num(df):
    m = {}
    for i in df:
        m[i] = w2n.word_to_num(i)
    return m

In [140]:
# !! JUST TESTING FUNCTIONS !!
# df.experience.apply(convert_to_num)

exp_map = map_words_to_num(df.experience)
exp_map
# !! JUST TESTING FUNCTIONS !!

{'zero': 0,
 'five': 5,
 'two': 2,
 'seven': 7,
 'three': 3,
 'ten': 10,
 'eleven': 11}

In [141]:
df.experience= df.experience.apply(convert_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [142]:
# PROCESSING test score column
df.rename(columns={'test_score(out of 10)':'test_score_by_10'},inplace=True)
df

experience  test_score_by_10  interview_score(out of 10)  salary($)
0           0               8.0                           9      50000
1           0               8.0                           6      45000
2           5               6.0                           7      60000
3           2              10.0                          10      65000
4           7               9.0                           6      70000
5           3               7.0                          10      62000
6          10               NaN                           7      72000
7          11               7.0                           8      80000

In [145]:
import math 
median_test_score = math.floor(df.test_score_by_10.mean())
median_test_score


7

In [147]:
df.test_score_by_10.fillna(median_test_score,inplace=True)
df

experience  test_score_by_10  interview_score(out of 10)  salary($)
0           0               8.0                           9      50000
1           0               8.0                           6      45000
2           5               6.0                           7      60000
3           2              10.0                          10      65000
4           7               9.0                           6      70000
5           3               7.0                          10      62000
6          10               7.0                           7      72000
7          11               7.0                           8      80000

In [148]:
# RENAMING interview score column
df.rename(columns={'interview_score(out of 10)':'interview_score_by_10'},inplace=True)
df

experience  test_score_by_10  interview_score_by_10  salary($)
0           0               8.0                      9      50000
1           0               8.0                      6      45000
2           5               6.0                      7      60000
3           2              10.0                     10      65000
4           7               9.0                      6      70000
5           3               7.0                     10      62000
6          10               7.0                      7      72000
7          11               7.0                      8      80000

In [149]:
# TRAIN MODEL

reg = linear_model.LinearRegression()
# target variable = 'salary($)'
# independent variables = 'experience','test_score_by_10','interview_score_by_10'

reg.fit(df[['experience','test_score_by_10','interview_score_by_10']],df[['salary($)']])

LinearRegression()

In [150]:
reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [151]:
reg.intercept_

array([14992.65144669])

In [152]:
reg.predict([[2,9,6]])

array([[53713.86677124]])

In [153]:
reg.predict([[12,10,10]])

array([[93747.79628651]])