In [15]:
from sklearn.datasets  import load_iris
from sklearn import svm
import pandas as pd

import numpy as np

In [4]:
iris = load_iris()

In [5]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)

In [6]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x:iris.target_names[x])

df[40:150]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
40                 5.0               3.5                1.3               0.3   
41                 4.5               2.3                1.3               0.3   
42                 4.4               3.2                1.3               0.2   
43                 5.0               3.5                1.6               0.6   
44                 5.1               3.8                1.9               0.4   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
40      setosa  
41      setosa  
42      setosa  
43      setosa  
44      setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[110 rows x 5 columns]

MANUAL APPROACH 

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [8]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9777777777777777

ANOTER APPROACH

USE K FOLD CROSS VALIDATION MANUALLY


In [10]:
from sklearn.model_selection import cross_val_score 
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data, iris.target, cv=5)


array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

NOW WE TRY USING FOR LOOP

In [16]:
kernels = ['rbf','linear']
C=[10,20,30]

avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_scores[kval+'_'+str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

NOW WE USE GridSearchCV approach

In [17]:
from sklearn.model_selection import GridSearchCV

In [19]:
clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00119696, 0.00159612, 0.00199327, 0.00099769, 0.00159612,
        0.00059838]),
 'std_fit_time': array([3.98946019e-04, 4.88831249e-04, 6.31061068e-04, 3.87384339e-07,
        7.98296976e-04, 1.19676590e-03]),
 'mean_score_time': array([0.00099711, 0.00059848, 0.0007978 , 0.00119667, 0.00079765,
        0.00079141]),
 'std_score_time': array([6.28991411e-07, 4.88655508e-04, 3.98898506e-04, 3.99088899e-04,
        7.45881504e-04, 3.95899650e-04]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 

In [20]:
# STORE THE RESULTS INTO A DATAFRAME 
results = pd.DataFrame(clf.cv_results_)

In [21]:
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001197  3.989460e-04         0.000997    6.289914e-07      10   
1       0.001596  4.888312e-04         0.000598    4.886555e-04      10   
2       0.001993  6.310611e-04         0.000798    3.988985e-04      20   
3       0.000998  3.873843e-07         0.001197    3.990889e-04      20   
4       0.001596  7.982970e-04         0.000798    7.458815e-04      30   
5       0.000598  1.196766e-03         0.000791    3.958996e-04      30   

  param_kernel                         params  split0_test_score  \
0          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
2          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 30, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.900000           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.900000           0.933333                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.900000                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.973333        0.038873                2  
2         0.966667        0.036515                3  
3         0.966667        0.042164                4  
4         0.960000        0.038873                5  
5         0.960000        0.048990                5

In [24]:
# GET THE SIGNIFICANT COLUMNS

results[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf         0.980000
1      10       linear         0.973333
2      20          rbf         0.966667
3      20       linear         0.966667
4      30          rbf         0.960000
5      30       linear         0.960000

In [25]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [26]:
clf.best_score_

0.9800000000000001

In [27]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. This is useful when you have too many parameters to try and your training time is longer. It helps reduce the cost of computation

In [28]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(svm.SVC(gamma='auto'),{
        'C':[10,20,30],
        'kernel':['rbf','linear']
    },
    cv=5,
    return_train_score=False,
    n_iter=2
)

rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      30       linear         0.960000

TRY WITH DIFFERENT ML MODELS AND DIFFERENT HYPERPARAMETERS AS WELL

In [29]:
# import the MODELS WE WANT TO CHECK

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [31]:
# STORE THE SCORES INTO A LIST
scores = []

for model_name, mp in model_params.items():
    clf= GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })
    
ms = pd.DataFrame(scores,columns=['model','best_score','best_params'])
# CHECK THE MODEL SCORES
ms

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}